// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://millycjkhnxhzngdekbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pbGx5Y2praG54aHpuZ2Rla2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzQ5NjgsImV4cCI6MjA1OTQ1MDk2OH0.3jxRpB-soQlrd0ZfYCUaQhKuqf_os3eVl9MrdAB0qKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);